export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const GET_MOVIE = 'GET_MOVIE';
export const ENABLE_BACK_BUTTON = 'ENABLE_BACK_BUTTON';
export const HANDLE_TYPING = 'HANDLE_TYPING';
